name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3

      - name: Налаштування AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name confused-jazz-otter

      - name: Логін у Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "dasakaton" --password-stdin

      - name: Завантаження Docker-образу з Docker Hub
        run: docker pull dasaskaton/app:latest

      - name: Деплой у Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
